image:
  repository: helxplatform/dug
  tag: "2.2.0"
  pullPolicy: IfNotPresent

web:
  appName: webserver
  deployment:
    apiPort: 5551
    apiWorkers: 4
    apiTimeout: 10
    extraEnv: []
    logLevel: INFO
    imagePullSecrets: []
    resources: {}
  service:
    name: search-api
    type: ClusterIP
    annotations: {}
    apiPort: "5551"
  debug: false

elasticsearch:
  enabled: true

redis:
  enabled: true

nboost:
  enabled: false
  host: api-nboost