apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.web.app_name}}
  name: {{ include "api.web.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.web.app_name}}
  template:
    metadata:
      labels:
        app: {{ .Values.web.app_name}}
    spec:
      {{- with .Values.web.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        name: {{ include "api.web.fullname" . }}-container
        env:
        - name: ELASTIC_API_HOST
          value: {{ .Values.elasticsearch.host }}
        - name: ELASTIC_API_PORT
          value: {{ .Values.elasticsearch.port | quote }}
        - name: ELASTIC_USER
          value: {{ .Values.elasticsearch.user }}
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.elasticsearch.existingSecret }}
              key: password
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.existingSecret }}
              key: password
        - name: NBOOST_API_HOST
          value: {{ .Values.nboost.host }}
        {{- if .Values.web.extraEnv }}
        {{ toYaml .Values.web.extraEnv }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.web.api_port }}
        command: [
                   "python",
                   "-m",
                   "dug.api",
                   "--debug",
{{/*            "gunicorn",*/}}
{{/*            "--workers={{ .Values.web.api_workers | default 4 }}",*/}}
{{/*            "--name=helx-search",*/}}
{{/*            "--bind=0.0.0.0:{{ .Values.web.api_port }}",*/}}
{{/*            "--timeout={{ .Values.web.api_timeout }}",*/}}
{{/*            "--log-level={{ .Values.web.log_level | default "INFO"}}",*/}}
{{/*            "--enable-stdio-inheritance", "--reload", "api.api:app"*/}}
        ]
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}