apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-api.web.fullname" . }}
  labels:
    app: {{ .Values.web.appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.web.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.web.appName}}
    spec:
      {{- with .Values.web.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "search-api.web.fullname" . }}-container
        env: {{ include "search-api.web.deploymentEnv" . | nindent 10 }}
        ports:
          - containerPort: {{ .Values.web.deployment.apiPort }}
        command: [
            "gunicorn",
            "--workers={{ .Values.web.deployment.apiWorkers | default 4 }}",
            "--name=helx-search",
            "--bind=0.0.0.0:{{ .Values.web.deployment.apiPort }}",
            "--timeout={{ .Values.web.deployment.apiTimeout }}",
            "--log-level={{ .Values.web.deployment.logLevel | default "INFO"}}",
            "--enable-stdio-inheritance", "--reload", "dug.api:app"
        ]
        resources:
          {{- toYaml .Values.web.deployment.resources | nindent 10 }}